"""Explicações por tela e por campo — pedido do Otávio (13/07): gestores em
validação precisam entender cada métrica e os insights que ela dá.

PADRÃO DE LINGUAGEM (Otávio 16/07 — 'os helps estão técnicos demais'): escrever
para o gestor NÃO técnico. Todo texto segue 3 blocos, um por linha (\n):
  O que mostra: o que a seção é, em uma frase.
  Como ler: cada variável/coluna explicada em palavras do dia a dia
    (nada de jargão sem tradução: mediana = valor típico/do meio; MRR =
    receita que se repete todo mês; coorte = acompanhar o mesmo grupo).
  Fique de olho: os insights numerados que o gestor encontra ali.
Rótulos aceitos também: Como usar / Como funciona / Para que serve /
Por que importa / Atenção. O renderizador (_fmt_help) põe cada linha num
bloco com o rótulo em negrito.

Estrutura: HELP["area/view"] = [("_intro", texto geral da página)] +
[(título-âncora da seção, explicação)]. O título-âncora casa com o <h2> real
da tela (tokens, sem acento); o que não casa cai no painel do topo.
Para editar/adicionar textos, só mexer aqui.
"""
from __future__ import annotations

import re
import unicodedata
from html import escape

HELP: dict[str, list[tuple[str, str]]] = {
    # ============================== GROWTH ==============================
    "growth/contas": [
        ("_intro", "O que mostra: todos os clientes que a IA acompanha. Cada linha é um cliente com uma nota de saúde de 0 a 100 — quanto MAIOR a nota, mais saudável a relação. A nota nasce de três fontes: o tom das conversas de WhatsApp, o andamento das entregas no ClickUp e sinais de risco (reclamações, silêncio prolongado).\nPara que serve: decidir quem o gestor atende PRIMEIRO hoje. Use os filtros do topo para ver só um squad, uma faixa de risco ou um serviço."),
        ("Contas por risco", "O que mostra: a carteira ordenada do maior risco para o menor (nota baixa = mais chance de cancelar). A borda colorida à esquerda de cada cartão segue a faixa de risco.\nComo ler: Score = a nota de saúde (0 a 100). Estágio = a fase da relação (saudável → desengajamento → insatisfação → intenção de saída; este último só aparece quando o cliente FALOU em cancelar). Trajetória = a direção (melhorando, estável ou piorando). Serviço-Squad (ex.: ADS-B3-S2) = o serviço contratado e o time que atende. MRR = quanto o cliente paga por mês. Execução = a saúde das entregas no ClickUp. Atrasos = se há tarefa com prazo vencido. Os selos de Execução e Atrasos são CLICÁVEIS — abrem o card do cliente no ClickUp para conferir as tarefas.\nFique de olho: (1) comece o dia pelos 'intenção de saída' e pelos críticos; (2) cliente mediano PIORANDO merece mais atenção que cliente ruim estável — nele ainda dá tempo de agir; (3) vários clientes piorando no mesmo squad = o problema é do processo do time, não dos clientes; (4) o botão Relatório abre o dossiê completo para levar à reunião."),
        ("Registrar desfecho", "O que mostra: o seletor 'desfecho…' que existe em cada conta.\nComo usar: quando uma conta em risco se resolve, registre o que aconteceu de verdade — retida, cancelada ou em negociação (com observação opcional; fica registrado quem lançou).\nFique de olho: esse registro alimenta a seção 'Precisão do modelo' (aba Alertas), que mede se a ferramenta acerta. Registre no dia da decisão do cliente — lançar com atraso distorce a conta de quanto dinheiro a ferramenta ajudou a salvar."),
    ],
    "growth/alertas": [
        ("_intro", "O que mostra: a fila de trabalho da retenção. Cada alerta é um cliente que cruzou um limite de risco e precisa de ação.\nComo funciona: o fluxo é reconhecer (alguém do time assume) → tratar → resolver (registrando o desfecho). Caso salvo vira exemplo no Playbook. A última anotação de cada caso também aparece no relatório individual do cliente."),
        ("Fila de retenção", "O que mostra: os alertas abertos, do mais grave para o menos grave.\nComo ler: crítico = o cliente falou em cancelar ou a nota despencou — agir HOJE (sem contato na semana, a decisão dele se consolida). Alto e atenção = insatisfação relevante, com um pouco mais de tempo para reagir.\nFique de olho: (1) esta fila é a agenda de retenção do dia; (2) alerta antigo que ninguém reconheceu = furo de processo do time; (3) a última nota mostra como está a tratativa sem precisar abrir o caso."),
        ("Ações recentes", "O que mostra: o histórico de quem fez o quê — quem reconheceu ou resolveu cada alerta, e quando.\nFique de olho: o tempo entre o alerta nascer e alguém agir é a 'velocidade da retenção' — quanto mais rápido o primeiro contato, maior a chance de reverter o cancelamento."),
        ("Precisão do modelo", "O que mostra: se os alertas da ferramenta estão ACERTANDO. Compara o que o modelo previu com o que aconteceu de verdade: das contas alertadas, quantas cancelaram mesmo, quantas foram salvas (e quantas dessas tiveram ação do time registrada) e quanta receita mensal foi retida depois do alerta.\nComo funciona: essa medição só existe se o time registrar o desfecho real de cada conta alertada (seletor 'desfecho…' da aba Contas).\nFique de olho: (1) conta salva SEM nenhuma ação do time registrada pode ser alarme falso do modelo — confirme antes de concluir; (2) a receita retida é o argumento de valor da ferramenta: 'o modelo avisou X, o time salvou Z'; (3) o modelo não se recalibra sozinho — aqui é só medição, por decisão nossa."),
        ("Evolução do risco da carteira", "O que mostra: uma foto por dia do risco da carteira — quantos alertas abertos de cada gravidade e quanta receita mensal está nas faixas alto/crítico.\nPara que serve: responder se as ações do time estão REDUZINDO o risco ao longo das semanas, ou só apagando incêndio.\nFique de olho: (1) críticos caindo mas receita em risco estável = estamos salvando contas pequenas e deixando as grandes — inverta a prioridade; (2) leia a tendência de semanas, não o sobe-e-desce do dia a dia; a série começou em 14/07/26."),
    ],
    "financeiro/visao": [
        ("_intro", "O que mostra: o planejado × o realizado da receita (planilha Planejamento_Receita_2026) mais os números ao vivo do Pipedrive.\nComo ler: três blocos — o mês corrente em tempo real contra a meta (estamos no ritmo?), o histórico dos meses fechados e as metas dos próximos meses.\nAtenção: recebimento e inadimplência ainda não têm fonte em tempo real (até os dados do Omie entrarem) — acompanhe pelo histórico mensal. Os números do Pipedrive foram conferidos ao centavo com a validação manual do gestor (15/07)."),
        ("Mês em tempo real × meta", "O que mostra: o funil e os contratos fechados (bookings) do mês, ao vivo do Pipedrive (mesma régua do funil de Marketing; atualiza a cada ~10 min).\nComo ler: o verde/vermelho compara duas porcentagens — quanto da meta já foi atingido × quanto do mês já passou. Verde = no ritmo de bater a meta, ou acima.\nFique de olho: (1) receita no ritmo mas POUCOS contratos = estamos vendendo planos mais caros que o previsto — confira o mix por plano; (2) funil no ritmo mas contratos atrasados = o gargalo é o fechamento — ver a área de Vendas."),
        ("O que mais afasta da meta", "O que mostra: os 3 maiores desvios do mês em R$ (contra o ritmo esperado), cada um com a causa provável e um clique para o diagnóstico.\nComo ler: desvio de um plano abre o Raio-X daquele bundle (a cadeia completa: aquisição → fechamento → retenção → operação); desvio de taxa abre a Ponte PV→Vendas; desvio de leads abre as Metas de Marketing. A 'causa provável' é uma heurística (faltam oportunidades × conversão baixa) — o diagnóstico de verdade está no clique.\nFique de olho: este bloco transforma o placar em ponto de partida de investigação — comece o mês por aqui; os valores são o TAMANHO do desvio, não uma promessa de recuperação."),
        ("Histórico realizado", "O que mostra: os meses já fechados, direto da planilha — quanto entrou, que parte é recorrente (se repete todo mês), inadimplência, contratos × meta e cancelamentos.\nFique de olho: % recorrente subindo + inadimplência caindo = a qualidade da receita está melhorando, mesmo que o total oscile de um mês para outro."),
        ("Metas — mês corrente e próximos", "O que mostra: o plano dos próximos meses, plano a plano (quantidade e valor) e o funil projetado — e, na coluna do MÊS ATUAL, o realizado ao vivo na frente de cada meta.\nComo ler: no mês atual cada célula vira 'realizado / meta' — verde = no ritmo de bater (comparando com a fração do mês já decorrida), vermelho = atrás do ritmo. Bookings por plano e funil vêm do Pipedrive ao vivo; recebimento, inadimplência e churn seguem só como projeção (sem fonte em tempo real até o Omie entrar). O link 'por quê?' ao lado de cada plano abre o Raio-X daquele bundle — a cadeia completa que explica o número; a taxa Oportunidade→Booking linka para a Ponte, e o churn para os Cancelamentos.\nFique de olho: (1) a meta de leads cresce mês a mês — se a taxa planejada de Oportunidade→Booking (15%) não se confirmar no realizado, a meta de contratos fica em risco antes do fim do trimestre; (2) B3-B5 vermelhos com o total verde = o mix está vindo de planos baratos — olhar o Forecast de Vendas."),
        ("Recebimento mês a mês", "Como ler: barra clara = tudo que foi recebido no mês; a barra escura dentro dela = a parte recorrente (que se repete todo mês; o % está indicado); linha tracejada = o que a planilha projetava.\nFique de olho: (1) a barra escura crescendo mais rápido que a clara = receita cada vez mais previsível — bom sinal; (2) o total caiu mas o recorrente ficou estável = perda pontual (serviço avulso), menos grave que perder base."),
        ("Bookings × meta mês a mês", "Como ler: cada barra é um mês de contratos fechados. Verde = meta batida; vermelha = abaixo; o tracinho marca onde a meta estava; meses futuros aparecem vazados (só a meta). O número de contratos está embaixo de cada mês.\nFique de olho: vários meses vermelhos mas com a QUANTIDADE de contratos em dia = o problema é o valor dos contratos (muito plano barato no mix), não o volume de vendas."),
        ("Inadimplência e churn", "Como ler: um chip colorido por mês. Inadimplência: verde até 4%, amarelo até 8%, vermelho acima. Cancelamento (churn): verde até 5%, amarelo até 9%. Meses futuros mostram o alvo, esmaecidos.\nFique de olho: inadimplência e cancelamento subindo JUNTOS costuma indicar o mesmo grupo de clientes com problema de cobrança ou de valor percebido — cruze com a aba Cancelamentos do Growth."),
    ],
    "financeiro/receita": [
        ("_intro", "O que mostra: a saúde da receita recorrente — a parte da receita que se repete todo mês.\nComo ler: ISR = a base recorrente deste mês dividida pela do mês anterior, vezes 100 (100 ou mais = a base está crescendo). Quick Ratio = receita nova dividida pela receita perdida (1 ou mais = o que entra repõe o que sai). São duas visões separadas de propósito: 'B2-B5' mostra só o modelo novo de planos; 'Consolidado' mostra o caixa total, incluindo os planos antigos em descontinuação. A estrela ★ marca o mês projetado em que o B2-B5 passa a sustentar a receita sozinho."),
    ],
    "growth/carga": [
        ("_intro", "O que mostra: tudo sobre os TIMES num lugar só — o ranking dos squads com pontos fortes/fracos e plano de ação, a carga de risco de cada um, a capacidade de atendimento (o time dá conta da carteira?) e as atividades em atraso.\nComo ler: os squads são os da planilha de composição (Bx-Sy); o líder de cada squad é o Growth.\nAtenção: o ranking orienta prioridade de gestão; as seções de carga e capacidade servem para decidir alocação e reforço — não para apontar culpados."),
        ("Ranking e análise", "O que mostra: uma nota geral de 0 a 100 por squad, combinando três coisas: relacionamento (vale 50% — a média das notas de saúde dos clientes do squad), execução (25% — o andamento das entregas no ClickUp) e risco (25% — a fatia de clientes em alerta).\nComo ler: cada card traz os pontos fortes e fracos do time (incluindo a carga por pessoa e a concentração de receita em risco), a dor mais comum da carteira e um plano de ação sugerido.\nFique de olho: (1) o 1º do ranking é fonte de boas práticas — vale documentar o que ele faz de diferente; (2) o último do ranking com ponto fraco de 'carga' = antes de cobrar execução, resolva a alocação — pode ser gente de menos para clientes demais."),
        ("Carga de risco por squad", "O que mostra: quanto risco cada squad carrega hoje.\nComo ler: Contas = clientes do squad. MRR = a soma do que esses clientes pagam por mês. Crít./Alto/Aten. = alertas abertos, por gravidade. MRR em risco = a receita dos clientes nas faixas alta/crítica (e que fatia do risco total da empresa está nesse squad). Exec. crítica = clientes com nota de execução muito baixa (entregas vencidas ou implantação além do prazo — a causa aparece ao passar o mouse). As bolinhas coloridas mostram quantos clientes há em cada faixa de saúde. Chip 'concentração de risco' = 3 ou mais clientes críticos, ou 30%+ da receita em risco, num squad só.\nFique de olho: (1) squad com o chip = pauta da semana da coordenação; (2) muitos críticos de valor baixo e poucos críticos de valor alto pedem respostas diferentes — o segundo caso pede reforço imediato."),
        ("Capacidade de atendimento", "O que mostra: se o tamanho de cada time é compatível com a carteira E com a carga de trabalho que ele atende.\nComo ler: Pessoas = tamanho do time (da planilha de composição). Contas/pessoa = quantos clientes cada pessoa atende, em média. Tarefas abertas = as tarefas ativas do squad no ClickUp (clientes pausados por inadimplência/concluídos não contam — serviço suspenso não é carga); Tarefas/pessoa = a carga REAL de trabalho — como há tarefas recorrentes (semanais ou mais), um squad pode ter MAIS contas e MENOS trabalho que outro; por isso as duas medidas ficam lado a lado (vermelho = bem acima da média dos squads; verde = bem abaixo). MRR/pessoa = a receita sob responsabilidade de cada pessoa. Graves/pessoa = alertas graves por pessoa. % saudável = a fatia da carteira em faixa boa. Chips: 'sobrecarga' = contas/pessoa bem acima da média · 'folga' = bem abaixo.\nFique de olho: (1) leia contas/pessoa e tarefas/pessoa JUNTAS — squad no topo de uma e não da outra indica mix de clientes com mais (ou menos) tarefas recorrentes, e a leitura automática avisa quando os líderes divergem; (2) sobrecarga + muitos críticos = redistribuir clientes entre squads do mesmo plano antes de pensar em contratar; (3) folga com carteira saudável = squad candidato a absorver clientes; (4) isto mede PROPORÇÃO, não esforço individual — use para desenhar o time, não para cobrar pessoas."),
        ("Atividades em atraso", "O que mostra: as tarefas abertas no ClickUp cujo prazo já venceu (as mesmas da coluna 'Atrasos' da aba Contas), somadas por squad e por responsável. Clientes pausados por inadimplência ou concluídos no ClickUp ficam FORA destas contagens (o serviço está suspenso — a tarefa vencida não é cobrança do squad; uma nota abaixo da tabela diz quantas ficaram de fora, e elas voltam a contar se o cliente reativar). Cliente com mais de uma conta no painel (ex.: conta do bundle + conta ADS) tem cada tarefa contada UMA vez, na conta principal — sem dupla contagem.\nComo ler: Tarefas atrasadas = o total de tarefas vencidas do squad. Contas com atraso = em quantos clientes elas estão (e o % da carteira afetada). Atrasos/pessoa = as tarefas vencidas divididas pelo tamanho do time — fica ao lado de Contas/pessoa (a mesma medida da seção Capacidade) de propósito: dá para ver se quem mais atrasa é também quem mais carrega. Maior atraso = há quantos dias venceu a tarefa mais antiga. Chips (só para squads que atrasam bem acima da média): 'capacidade' = atrasa E carrega mais que a média — o atraso combina com sobrecarga, redistribuir ou reforçar; 'ritmo/processo' = atrasa SEM carregar mais que a média — o gargalo não é falta de gente, é rotina e priorização.\nComo usar: clique no nome de um squad ou de um responsável para abrir a lista das tarefas atrasadas daquele caso (da mais antiga para a mais recente); cada tarefa tem link direto para ela no ClickUp — dá para cobrar apontando exatamente qual entrega venceu.\nFique de olho: (1) a leitura no topo já responde se, no geral, os atrasos acompanham a carga ou não; (2) o responsável no topo do ranking pode estar sobrecarregado OU segurando tarefas dos outros — valide com o Growth do squad antes de cobrar; (3) tarefa vencida SEM responsável = ninguém está sendo cobrado por ela — atribuir um dono é a ação mais barata da lista; (4) muitas tarefas com poucos dias = acúmulo recente; poucas tarefas com muitos dias = abandono antigo."),
    ],
    "growth/cancelamentos": [
        ("_intro", "O que mostra: a visão oficial dos cancelamentos (números conferidos com as planilhas do time — batem com a contagem da gestão).\nComo ler: volume por mês, taxa por plano, receita perdida, tempo de casa e motivos — com filtro de período no topo.\nPara que serve: separar ONDE o cancelamento dói (qual plano, que época, quão cedo) para atacar a causa certa."),
        ("Saídas por mês", "O que mostra: quantos clientes cancelaram em cada mês (contagem oficial).\nFique de olho: a tendência importa mais que um mês isolado — queda sustentada = a retenção está funcionando."),
        ("Evolução mensal", "Como ler: o total de cancelamentos dividido em clientes NOVOS (até 3 meses de casa) e ANTIGOS.\nFique de olho: muitos cancelamentos precoces = problema no início da jornada (expectativa criada na venda, ou onboarding); cancelamentos tardios = problema de valor contínuo e relacionamento. Cada um tem dono e remédio diferentes."),
        ("MRR perdido por mês", "O que mostra: a receita mensal que saiu junto com os cancelamentos.\nFique de olho: mês com POUCOS cancelamentos mas MUITA receita perdida = saíram contas grandes — investigue cada uma no relatório individual."),
        ("Taxa de cancelamento por bundle", "O que mostra: a taxa de cancelamento de cada plano em DUAS visões — por número de clientes e por faturamento (a receita mensal que saiu em relação à receita da base).\nComo ler: Base ativa e MRR da base = os clientes monitorados hoje e quanto pagam por mês. Saídas e MRR perdido = o que saiu no período filtrado. Taxa clientes = saídas divididas pela base (média mensal). Taxa faturamento = receita perdida dividida pela receita da base — se ela for maior que a taxa de clientes, estamos perdendo contas GRANDES. A linha 'Taxa GERAL — recorrentes' é a taxa oficial da empresa e NÃO inclui o B1: é plano semestral pago à vista, não recorrente (por isso decks antigos com números diferentes — a régua certa exclui o B1).\nFique de olho: (1) taxa alta num plano específico = revisar preço, entrega ou perfil de cliente daquele plano; (2) taxa por faturamento acima da taxa por clientes = as contas que saem são maiores que a média — priorize retenção nas contas grandes; (3) a base é a ATUAL (não temos a base histórica mês a mês) — em períodos longos a taxa é aproximação, e num plano cuja base ENCOLHEU (ex.: B5 com 9 contas hoje) a taxa sai alta mesmo sem saídas recentes, porque divide as saídas antigas pela base pequena de agora; a barra avisa '⚠ base pequena/encolheu' nesses casos — confira as saídas por mês antes de concluir; (4) o ≈ marca base de MRR ESTIMADA: nem toda conta tem valor lançado (20-56% por plano), então usamos a média das preenchidas × total — lançar o MRR das contas melhora essa visão."),
        ("Tempo de casa na saída", "O que mostra: quanto tempo o cliente ficou antes de cancelar, por plano.\nFique de olho: se a maioria sai com 3 meses ou menos, o problema começa na venda (expectativa) ou no onboarding — antes de o cliente chegar ao gestor de contas."),
        ("Motivos informados", "O que mostra: o que o time registrou como causa de cada cancelamento.\nFique de olho: (1) o motivo mais frequente merece um plano de resposta pronto (playbook); (2) muitos '(sem motivo)' = disciplina de registro a cobrar do time."),
        ("Por plano e por equipe", "O que mostra: o cruzamento plano × squad — onde os cancelamentos se concentram.\nFique de olho: cancelamento concentrado num squad, com planos variados = questão de equipe; concentrado num plano, em vários squads = questão de produto ou preço."),
        ("Fila de retenção (tratativas)", "O que mostra: os clientes em TRATATIVA de cancelamento neste mês — o pipeline de retenção, onde ainda dá para agir antes de formalizar.\nComo ler: a situação vem da planilha do time ('vai formalizar', 'em negociação', 'revertido'...). Sem situação registrada = cobrar atualização de quem atende.\nFique de olho: tratativa parada sem situação há dias costuma virar cancelamento silencioso — é a lista de cobrança da semana."),
    ],
    "growth/playbooks": [
        ("_intro", "O que mostra: a biblioteca viva de retenção — cada ação registrada pelo time (o que foi feito, com qual cliente, com que resultado). Casos salvos viram referência para repetir."),
        ("Práticas de referência", "O que mostra: as ações que REVERTERAM um cancelamento, com o contexto de cada caso.\nFique de olho: antes de improvisar numa tratativa nova, procure aqui um caso parecido (mesmo estágio ou motivo) e repita o que já funcionou."),
    ],
    "growth/relatorios": [
        ("_intro", "O que mostra: os relatórios consolidados da área — o resumo executivo (com envio ao Slack) e o relatório multi-cliente de Assessoria. É daqui que saem os materiais das reuniões de gestão."),
        ("Análise por squad", "Mudou de lugar (15/07): o ranking por squad, com pontos fortes/fracos e plano de ação, agora vive na aba 'Análise dos Squads', junto com carga de risco e capacidade de atendimento."),
        ("Relatório de Assessoria", "O que mostra: a saúde e as entregas de cada cliente da assessoria, num documento só.\nFique de olho: use na reunião semanal do time para revisar a carteira inteira em 15 minutos."),
    ],
    # ============================= MARKETING ============================
    "marketing/visao": [
        ("_intro", "O que mostra: o painel executivo da aquisição no mês — os principais números contra o mês anterior, o funil completo contra as metas e o que falta nos planos prioritários (B3-B5).\nPara que serve: responder em 30 segundos — estamos no ritmo? Onde está o gargalo? O que falta nos planos que mais importam?"),
        ("Funil do mês vs meta", "Como ler: cada etapa do funil (Lead → MQL → SAL → SQL → Oportunidade → Booking) contra a meta do mês. O traço vertical marca onde a barra deveria estar pelo dia de hoje — barra antes do traço = etapa atrasada.\nFique de olho: (1) a PRIMEIRA etapa abaixo do traço é o gargalo real — as seguintes só herdam o problema dela; (2) topo no ritmo + fundo atrasado = problema de conversão (Pré-vendas/Vendas), não de volume; (3) tudo atrasado = problema de geração de leads (verba ou campanha)."),
        ("Progresso vs meta do mês", "Como ler: compara o % da meta já realizado com o % do mês já decorrido. Verde = tendência de bater a meta; vermelho = precisa de ação AINDA ESTE MÊS (mais verba, destravar campanha) — esperar o fechamento é tarde demais."),
        ("Gap para a meta (B3-B5)", "O que mostra: quanto falta para a meta dos planos prioritários da empresa (os de maior valor).\nFique de olho: (1) este número é a pauta do trimestre — B1 no ritmo não compensa B4 parado; (2) use o Planejador para converter o que falta em leads e verba por canal."),
    ],
    "marketing/metas": [
        ("_intro", "O que mostra: as metas detalhadas do semestre (da planilha do time) contra o realizado — funil mês a mês, custo por etapa, investimento e oportunidades por canal. É a página de prestação de contas do plano do semestre."),
        ("Funil mês a mês", "Como ler: uma grade mês × etapa do funil, com realizado/meta e o ritmo de cada célula.\nFique de olho: os meses passados mostram o padrão de erro do planejamento (sempre otimista na mesma etapa?) — recalibre a meta, não só a execução."),
        ("Custo por etapa vs alvo", "O que mostra: quanto custou gerar cada lead e cada oportunidade, contra o custo planejado.\nFique de olho: (1) custo por lead dentro do alvo mas custo por oportunidade estourado = lead barato e fraco — problema de qualidade, não de preço; (2) compare os canais antes de cortar verba."),
        ("Investimento planejado × gasto", "O que mostra: a verba planejada contra a executada, mês a mês.\nFique de olho: gastar menos e bater a meta = eficiência — repita a receita; gastar menos e perder a meta = a operação de campanha travou — problema de execução, não de orçamento."),
        ("Oportunidades por canal", "O que mostra: planejado × realizado por canal (META, Prospecção, Eventos, Shopee, Low Ticket, Instagram Orgânico), pela origem registrada do lead.\nFique de olho: canal sempre abaixo do plano = replanejar o mix; sempre acima = candidato a verba extra."),
    ],
    "marketing/funil": [
        ("_intro", "O que mostra: o funil de prospecção com a MESMA régua do dashboard oficial do time (a que a gestão confere no Pipedrive).\nComo ler: Lead = negócios criados no período. MQL e SAL = leads descontando os desqualificados (nota baixa, sem retorno, dropshipping…). SQL = lead que passou para um closer (reunião agendada). Oportunidade = entrou em negociação no período — não acompanha a mesma turma de leads do mês, então pode até superar o SQL. Booking = contratos ganhos.\nAtenção: MQL/SAL/SQL mudam retroativamente — desqualificar um lead hoje altera o número do mês em que ele entrou."),
        ("Funil", "O que mostra: os volumes por etapa no período filtrado, no mesmo visual do dashboard do time.\nFique de olho: (1) compare períodos para enxergar sazonalidade; (2) a taxa que mais caiu em relação ao histórico é o alarme da semana."),
        ("Taxas por etapa", "Como ler: TX = a conversão de cada etapa em relação à anterior; TX Lead = em relação ao topo do funil.\nFique de olho: a taxa Lead→Booking é a eficiência do funil inteiro — se ela caiu, as taxas por etapa mostram exatamente onde."),
        ("Metas de taxa do mês", "O que mostra: as metas de conversão de cada etapa, editáveis por mês (vêm pré-preenchidas da planilha; a edição manual prevalece).\nFique de olho: a etapa mais distante da meta é onde investir treinamento e processo."),
        ("Como alcançar a meta", "O que mostra: sugestões automáticas geradas a partir da etapa mais distante da meta.\nFique de olho: é o ponto de partida da conversa, não a conclusão — valide com o contexto do time."),
    ],
    "marketing/canais": [
        ("_intro", "O que mostra: o ranking dos canais por volume de leads e conversão, com a variação contra o período anterior.\nPara que serve: decidir onde a verba sobe e onde desce com base em dado, não em impressão.\nFique de olho: canal com MUITO volume e conversão fraca desperdiça verba de mídia E tempo do time de Pré-vendas — segmente ou corte."),
    ],
    "marketing/origens": [
        ("_intro", "O que mostra: cada origem de lead com volume, conversão e um chip de decisão automático: ESCALAR (volume e conversão bons) ou REVISAR (volume alto, conversão fraca). Clique numa origem para ver o detalhe.\nFique de olho: os chips são a lista de decisões da semana de mídia; o filtro separa a mídia paga do orgânico."),
    ],
    "marketing/midia": [
        ("_intro", "O que mostra: o desempenho diário da mídia paga, mais a galeria de criativos com miniaturas.\nAtenção: leads e custo por lead usam os negócios REAIS do Pipedrive, não o número da plataforma de anúncios (que infla). CTR e impressões vêm da plataforma."),
        ("Leads por dia", "O que mostra: os leads criados por dia, atribuídos à mídia paga.\nFique de olho: queda brusca num dia específico = campanha pausada/reprovada ou verba esgotada — confira com o gestor de anúncios o que houve naquele dia."),
        ("Gasto por dia", "O que mostra: o investimento diário, somando as plataformas.\nFique de olho: gasto subindo com leads estáveis = cada lead saindo mais caro — criativo cansado ou leilão mais competitivo."),
        ("CPL por dia", "Como ler: CPL = custo por lead (o gasto dividido pelos leads reais do Pipedrive).\nFique de olho: compare com o alvo da aba Metas; 3 ou mais dias acima do alvo = trocar criativo/público já, sem esperar o mês fechar."),
        ("Criativos do período", "O que mostra: cada peça de anúncio com gasto, leads e custo por lead.\nFique de olho: os 20% melhores criativos costumam pagar a conta toda — identifique o padrão deles (formato, promessa, público) antes de encomendar os próximos."),
    ],
    "marketing/lag": [
        ("_intro", "O que mostra: quanto tempo o lead demora para virar contrato — no geral, por canal e por campanha.\nPara que serve: saber QUANDO o investimento de hoje vira receita — e não julgar campanha nova cedo demais.\nComo ler: três marcos de tempo — o lead rápido (os 25% mais rápidos), o típico (a mediana: metade converte antes, metade depois) e o lento (75%)."),
        ("Curva de acúmulo de leads", "Como ler: a curva mostra que % dos leads já converteu após X dias.\nFique de olho: se metade converte em ~30 dias, uma campanha lançada há 2 semanas ainda não mostrou nem metade do resultado — segure o julgamento."),
        ("Lag agregado por canal", "O que mostra: o tempo típico de conversão de cada canal.\nFique de olho: canal rápido (ex.: indicação) financia o caixa; canal lento precisa de fluxo constante — não fique ligando e desligando."),
        ("Por campanha", "O que mostra: o tempo de conversão de cada campanha.\nFique de olho: campanha muito mais lenta que o normal do canal = público frio ou qualificação lenta — ajuste a segmentação ou a cadência de Pré-vendas."),
    ],
    "marketing/planejador": [
        ("_intro", "O que mostra: o planejamento de trás para frente, por plano — diga quantos contratos de cada plano você quer e até quando; a ferramenta calcula quantos leads e quanta verba são necessários, no ritmo histórico de conversão e de tempo até fechar, e mostra quais campanhas e criativos já fecharam aquele plano antes."),
        ("Estratégias e criativos recomendados", "O que mostra: as campanhas e os criativos que já FECHARAM o plano pedido no passado.\nFique de olho: começar por eles reduz o risco do plano — é o caminho já pavimentado; o resto é aposta."),
    ],
    "marketing/criativos": [
        ("_intro", "O que mostra: a central de DECISÃO sobre criativos. Cada criativo recebe um veredito automático (escalar / manter / revisar / pausar) comparando com o desempenho típico do conjunto; os padrões vencedores viram sugestão de brief; e o cruzamento com o plano fechado mostra qual promessa traz o cliente certo.\nComo usar: siga a ordem — Leitura do especialista → vereditos → Elementos → brief novo."),
        ("Leitura do especialista", "O que mostra: as 3 decisões prontas — o criativo a escalar (converte bem acima do típico, com volume), o maior ralo de verba (gasta muito convertendo metade do normal) e o elemento vencedor para o próximo brief."),
        ("Desempenho por criativo", "Como ler: ESCALAR = conversão acima do típico do conjunto — merece mais verba. REVISAR = conversão fraca com gasto relevante — troque promessa/público antes de matar. PAUSAR = caro E fraco ao mesmo tempo.\nFique de olho: o veredito compara cada criativo com os DEMAIS DO FILTRO atual — filtre por público para comparar coisas comparáveis."),
        ("Elementos que funcionam", "O que mostra: o desempenho agregado por palavra no nome do criativo (vídeo, ugc, oferta, depoimento…).\nFique de olho: (1) elemento verde repetido em vários criativos = padrão comprovado — industrialize; (2) isso exige disciplina no nome dos anúncios — nomes crípticos deixam esta análise cega."),
        ("Criativo × plano fechado", "O que mostra: quais criativos geram contratos de cada plano — a promessa certa atrai o cliente certo.\nFique de olho: (1) chip 'traz B2-B5' = criativo alinhado à meta da empresa — priorize; (2) criativo que só fecha B1 pode estar prometendo preço em vez de valor; (3) cruze com a aba Ciclo de Vida: trazer cliente B2-B5 que cancela cedo não é vitória."),
        ("Histórico de testes", "O que mostra: os testes de criativo × público já rodados, com resultado.\nFique de olho: antes de aprovar um teste novo, confira se já não foi feito — orçamento de teste é finito."),
        ("Ideias", "O que mostra: sugestões geradas a partir dos padrões vencedores.\nFique de olho: use como brief inicial para a produção, não como peça final."),
    ],
    "marketing/ciclo": [
        ("_intro", "O que mostra: a ponte entre Aquisição e Retenção — cada cliente FECHADO é acompanhado da origem (canal, campanha, criativo) até o desfecho atual: ativo, cancelou cedo (até 3 meses) ou cancelou depois.\nAtenção: o vínculo entre venda e cancelamento é feito pelo NOME do cliente (a cobertura aparece no rodapé); cancelamentos anteriores a 2025 ficam de fora.\nPara que serve: a ação corretiva é de Marketing — cortar ou ajustar criativo que promete demais, rever a segmentação do canal que traz cliente que sai."),
        ("Desfecho por canal de origem", "Como ler: quantos clientes cada canal trouxe e quantos FICARAM, com a receita retida × perdida. CAC = quanto custou trazer cada cliente. CAC ajustado = esse custo dividido pela taxa de retenção — o custo real por cliente que FICA.\nFique de olho: (1) canal com CAC baixo mas CAC ajustado alto é a ilusão do canal barato — traz cliente que vai embora; (2) compare a receita retida, não só o volume."),
        ("Criativos que trazem churn precoce", "O que mostra: dentro da mídia paga, quais criativos trazem clientes que cancelam cedo.\nFique de olho: se concentra num criativo, o problema é a PROMESSA da venda, não a entrega. Com menos de 8 casos o dado aparece sem diagnóstico — amostra pequena demais para concluir."),
        ("Churn precoce por canal × plano", "O que mostra: de qual canal vêm os clientes de cada plano que saem cedo (fecha a descoberta do B2: 69% saem cedo).\nFique de olho: saída precoce alta num cruzamento canal × plano específico = ajustar a oferta desse plano nesse canal."),
        ("Safras por mês de fechamento", "Como ler: cada linha agrupa os clientes fechados no mesmo mês (a 'safra'). Safras recentes ainda não tiveram tempo de cancelar tardiamente — '(em maturação)' marca as parciais.\nFique de olho: compare safras FECHADAS entre si — comparar safra madura com safra nova induz a erro."),
    ],
    # ============================= PRÉ-VENDAS ===========================
    "prevendas/funil": [
        ("_intro", "O que mostra: o funil completo (Lead → Booking) na régua oficial do dashboard do time — os mesmos números das abas de Marketing e Vendas. O trabalho de Pré-vendas vai do Lead ao SQL (lead entregue ao closer = reunião agendada); Oportunidade e Booking mostram o destino do que a área gerou.\nPara que serve: os leads estão virando reunião? Onde morrem os que não viram?"),
        ("Funil completo", "Como ler: Lead = negócios criados no período → MQL = desconta os perdidos por nota baixa → SAL = desconta os demais motivos de desqualificação → SQL = lead cujo dono atual é um closer (reunião agendada, entregue a Vendas) → Oportunidade = entrou em negociação no período → Booking = contratos ganhos, com a receita.\nFique de olho: (1) MQL→SAL baixo = muito lead desqualificado — veja os motivos logo abaixo; (2) SAL→SQL baixo = lead aceito que não vira reunião — cruze com a velocidade do 1º contato; (3) as etapas de qualificação mudam retroativamente: o funil do mês ainda se move enquanto os SDRs tratam a fila."),
        ("Conversão por dia de chegada do lead", "O que mostra: a taxa de agendamento conforme o DIA DA SEMANA em que o lead entrou (a reunião conta mesmo que aconteça dias depois).\nFique de olho: (1) sexta e fim de semana convertendo bem menos = lead esfriando sem contato — caso para plantão reduzido ou resposta automática; (2) cruze com a aba Melhor Horário: dia que gera muito lead e converte pouco é onde a fila acumula; (3) taxas parecidas em todos os dias = a distribuição semanal da verba de mídia não precisa mudar."),
        ("Qualidade do lead por origem", "O que mostra: a taxa lead→reunião de cada canal de origem.\nFique de olho: (1) devolve o dado ao Marketing: canal que converte 3× mais merece verba; (2) SDR reclamando de 'lead ruim'? Aqui está a prova (ou não), origem por origem."),
        ("Motivos de desqualificação", "O que mostra: por que os leads morrem antes da reunião.\nFique de olho: motivo dominante do tipo 'sem faturamento mínimo' = o filtro deve ser feito NA CAMPANHA (formulário, segmentação) — não é falha do SDR."),
        ("Diagnóstico do especialista", "O que mostra: uma leitura automática no papel de um head de pré-vendas — taxa de contato, agendamento e desqualificação contra referências de mercado.\nFique de olho: é pauta pronta para a reunião semanal da coordenação."),
    ],
    "prevendas/speed": [
        ("_intro", "O que mostra: a velocidade do primeiro contato — o tempo entre o lead entrar e o primeiro toque registrado no Pipedrive.\nPor que importa: referência de mercado — contato em até 15 minutos multiplica a conversão. Inclui a fila de leads NUNCA tocados: dinheiro parado na mesa."),
        ("Velocidade do 1º contato × conversão", "Como ler: os leads agrupados pelo tempo até o 1º contato (até 15 min, 15-60 min, 1-4h, 4-24h, mais de 24h, sem contato). Agendaram = quantos viraram reunião (mesmo que dias depois). Taxa = a conversão de cada faixa.\nFique de olho: (1) a diferença de taxa entre 'até 15 min' e 'mais de 24h' é o preço, em reuniões, de cada lead esperando — argumento pronto para priorizar a fila; (2) a faixa 'sem contato' com taxa quase zero = verba de mídia desperdiçada — zere essa fila diariamente; (3) taxas parecidas entre as faixas = o problema da conversão não é velocidade — investigue a qualidade do lead por origem, no Funil."),
        ("Taxa de agendamento por tipo de 1º contato", "O que mostra: cada tipo de abordagem inicial (ligação, WhatsApp, cadência automática…) com leads, agendamentos e taxa.\nFique de olho: (1) tipo com taxa bem acima dos demais = vire a primeira tentativa padrão do time; (2) cadência automática com taxa baixa = reescrever a régua de mensagens, não abandonar; (3) muitos '(sem registro)' = cobrar disciplina de registro — sem isso esta leitura fica cega."),
        ("Por responsável do 1º contato", "O que mostra: o tempo típico de resposta e o % de leads atendidos em até 15 min, por SDR.\nFique de olho: (1) lentidão generalizada = problema de processo ou ferramenta; lentidão de UMA pessoa = carga ou disciplina; (2) compare com a taxa de agendamento — velocidade sem conversão indica abordagem a treinar."),
        ("Por origem", "O que mostra: a velocidade de resposta por canal de entrada do lead.\nFique de olho: canal sempre lento (ex.: leads chegando de madrugada) = caso para resposta automática ou revisão do horário do time — cruze com a aba Melhor Horário."),
        ("Evolução mensal (6 meses)", "O que mostra: a trajetória da Pré-vendas mês a mês — leads, SQLs, a taxa lead→SQL e a mediana do 1º contato.\nComo ler: a régua do funil é a oficial e retroativa (meses antigos são mais confiáveis que o corrente, que ainda amadurece). '—' no speed = mês anterior ao início da coleta de atividades.\nFique de olho: leia a TENDÊNCIA, não a foto — taxa caindo 2 meses seguidos com speed subindo é o sinal clássico de fila crescendo mais rápido que o time."),
    ],
    "prevendas/horarios": [
        ("_intro", "O que mostra: QUANDO as reuniões são agendadas (o momento em que o negócio entrou em 'Reunião Agendada', no horário de Brasília) — mapa de calor por dia e hora, as melhores janelas, o % fora do expediente e o recorte por plano.\nPara que serve: base objetiva para decidir horários de ligação e eventual extensão de expediente. O botão 'Gerar relatório' cria a versão para impressão."),
        ("Mapa de calor", "Como ler: células mais escuras = mais agendamentos naquele dia/hora.\nFique de olho: (1) as janelas de ouro são onde concentrar as tentativas de ligação; (2) ressalva: o horário registrado é o da movimentação do card — SDR que atualiza tudo em lote no fim do dia infla as últimas horas; a gestora sabe distinguir."),
        ("Agendamentos por colaborador × hora", "Como ler: o padrão de horário de cada pessoa. O sombreado é na escala DA PRÓPRIA PESSOA — dá para comparar padrões mesmo entre volumes muito diferentes.\nFique de olho: (1) pico de alguém numa janela fraca do time = método que funciona fora do óbvio — vale entender e testar com os demais; (2) alguém sem agendamentos nas janelas de ouro do time = revisar a agenda dela nesses horários (reunião interna? pausa?); (3) atenção aos avisos de amostra pequena e à atualização em lote."),
        ("Top 5 janelas", "O que mostra: as 5 combinações de dia + hora com mais agendamentos, e o % do total que elas concentram.\nFique de olho: se concentram muito volume, blinde esses horários na agenda do time — sem reunião interna, foco em ligação."),
        ("Taxa de agendamento por horário", "O que mostra: de cada 100 ligações concluídas naquele dia/hora, quantas viraram reunião agendada (agendamentos ÷ ligações). É o complemento do mapa de calor: o mapa mostra ONDE saem agendamentos; a taxa mostra onde a ligação RENDE mais.\nComo ler: célula mais escura = ligação converte mais ali. * = menos de 5 ligações na célula (amostra pequena — não conclua por ela). ∅ = agendamento sem ligação registrada (o card foi movido sem atividade de ligação no Pipedrive). — = nada aconteceu ali.\nFique de olho: (1) um horário com MUITOS agendamentos e taxa BAIXA costuma ser mutirão — houve muita ligação, não um horário melhor; o horário bom de verdade tem taxa alta com volume razoável; (2) a hora usada é a da CONCLUSÃO da atividade no Pipedrive — se o SDR marca as ligações como feitas em lote no fim do dia, a taxa distorce; cobre o registro na hora; (3) a ligação e o agendamento precisam ter acontecido na mesma janela para casar — é uma aproximação honesta, não um rastreio ligação-a-ligação; (4) o registro de ligações começa em meados de 2026 — ao filtrar períodos antigos, um aviso mostra a partir de quando a taxa vale, e numerador e denominador ficam restritos ao MESMO trecho (sem isso apareciam taxas impossíveis, tipo 4600%)."),
        ("Melhor horário por origem do lead", "O que mostra: o padrão de horário de agendamento separado pela ORIGEM do lead (Meta Ads, Prospecção, Google, Indicações…) — a mesma régua de canais da Origem de Leads do Marketing.\nComo ler: no MAPA, cada linha é uma origem e o sombreado é na escala DA PRÓPRIA origem (dá para comparar padrões entre volumes muito diferentes); a célula contornada é o pico da origem. A TABELA abaixo traz as 3 melhores janelas com o dia da semana (o mapa agrega os dias).\nFique de olho: (1) se o melhor horário de Meta for diferente do de prospecção, escale as tentativas de cada fila no horário certo — não trate a fila como uma coisa só; (2) * e aviso de amostra pequena = não mude a operação por meia dúzia de casos."),
        ("Melhores janelas por bundle", "O que mostra: a melhor janela pode variar por plano (o decisor de um B5 atende em horário diferente do de um B1).\nFique de olho: atenção ao aviso de amostra pequena — não mude a escala do time por meia dúzia de casos."),
        ("Melhores horários por taxa", "O que mostra: as janelas dia+hora onde a LIGAÇÃO mais converte em agendamento — o complemento do ranking por volume.\nComo ler: só entram janelas com 5 ou mais ligações (amostra confiável); a taxa usa apenas agendamentos de leads que TÊM ligação registrada — agendamento de indicação/inbound sem ligação fica FORA (senão a taxa estoura sem significar horário bom).\nFique de olho: janela com taxa alta E volume razoável é onde blindar a agenda dos SDRs; taxa alta com volume mínimo ainda é hipótese."),
    ],
    "prevendas/sdrs": [
        ("_intro", "O que mostra: a mesa da coordenação — uma tabela única por colaborador e planos de ação individuais. Os volumes seguem a régua oficial dos gráficos do Pipedrive (atribuição pelo campo SDR do negócio); a última coluna traz a velocidade do 1º contato. A lista do time é editável no Painel Administrativo."),
        ("Leads e oportunidades por colaborador", "Como ler: Leads = negócios criados no período. Oportunidades = entraram em negociação no período (podem vir de lead antigo). Bookings = contratos ganhos no período. Speed = o tempo típico até o 1º contato registrado.\nFique de olho: (1) estes números batem com os gráficos do Pipedrive; (2) '(sem SDR definido)' grande = leads ainda não distribuídos ou não tocados — é a fila a zerar (cruze com Speed-to-Lead); (3) conversão muito diferente entre SDRs de volume parecido = mix de origem ou abordagem — a velocidade ajuda a separar esforço de conversa; (4) desligados aparecem somados na linha '(ex-colaboradores)' para o total continuar batendo; (5) nomes 'fora do time de PV' têm negócios no nome mas não estão na lista da área — ajuste no Painel Administrativo se alguém entrou."),
        ("Motivos de desqualificação por SDR", "O que mostra: um card por pessoa com os motivos que mais derrubam os leads DELA.\nFique de olho: (1) motivo dominante em UMA pessoa = dificuldade específica de roteiro ou abordagem — material direto para o 1:1; (2) o mesmo motivo no topo de todas = é a qualidade do lead que chega — devolva ao Marketing; (3) % alto de '(sem motivo)' = disciplina de registro a cobrar."),
        ("Conversão por origem × SDR", "Como ler: a taxa lead→oportunidade de cada SDR em cada origem, comparada à média do time naquela origem (verde = bem acima; vermelho = bem abaixo; só vale com pelo menos 8 leads).\nFique de olho: (1) alguém muito forte numa origem = candidata a receber mais leads daquele tipo — e a ensinar o tratamento às demais; (2) fraqueza generalizada numa origem = o problema é o lead, não o time."),
        ("Oportunidades por plano × SDR", "O que mostra: quais planos as oportunidades de cada SDR carregam (% = participação no total dela).\nFique de olho: (1) mix concentrado em B1 quando a meta da empresa é B3-B5 = puxar a qualificação para cima; (2) quem gera B4-B5 com consistência domina a conversa de valor — vale documentar o roteiro dela."),
        ("Planos de ação individuais", "O que mostra: pontos fortes, fracos e ações sugeridas por pessoa, gerados por regra.\nFique de olho: leve para o 1:1 como ponto de partida — a coordenação contextualiza o que o número não vê (férias, mix de leads, rampagem)."),
    ],
    # ============================== VENDAS ==============================
    "vendas/funil": [
        ("_intro", "O que mostra: o funil do fechamento — da reunião agendada (entregue pela Pré-vendas) até o contrato, com a receita do período e a tendência mensal de conversão. Inclui o funil completo (Lead→Booking) na régua oficial do time.\nPara que serve: as reuniões estão virando contrato?"),
        ("Funil completo", "O que mostra: o funil inteiro (Lead → MQL → SAL → SQL → Oportunidade → Booking) na régua oficial — os mesmos números das abas de Marketing e Pré-vendas.\nFique de olho: (1) é a visão de contexto: quanto do resultado de Vendas é herança do topo do funil; (2) Oportunidade não acompanha a mesma turma de leads do mês — pode até superar o SQL; (3) para o detalhe do fechamento, use as seções abaixo."),
        ("KPIs do fechamento", "Como ler: Reuniões → Negociações → Contratos fechados, com a receita do período.\nFique de olho: (1) queda de Reunião→Negociação = no-show ou reunião fraca — cruze com os no-shows; (2) queda de Negociação→Contrato = proposta, preço ou urgência — veja os motivos de perda."),
        ("Tendência Oportunidade → Booking", "O que mostra: a conversão de negociação em contrato, mês a mês.\nFique de olho: conversão caindo com volume estável = problema de FECHAMENTO (time, proposta, concorrência), não de topo de funil — e o remédio é diferente de gerar mais lead."),
        ("Oportunidades por bundle", "Como ler: Oportunidades = negociações iniciadas no período, já com o plano definido (é nesse momento que o campo Produto é preenchido no Pipedrive). % do mix = a participação de cada plano nas oportunidades novas — o retrato do que o funil está produzindo. Bookings = contratos FECHADOS no período, por plano (mesma régua do controle da gestão). Oport→Booking = a eficiência de fechamento de cada plano.\nFique de olho: (1) mix concentrado em B1 com a meta em B3-B5 = o gargalo está na geração/qualificação, não no fechamento; (2) se a conversão cresce com o plano, UMA oportunidade B4 rende mais que várias B1 — priorize qualificar para cima; (3) plano com muitas oportunidades e conversão baixa = revisar proposta e preço daquele plano."),
        ("Conversões por origem × plano", "O que mostra: quais origens de lead FECHAM quais planos. TX = contratos divididos pelos leads da origem.\nFique de olho: (1) a origem que fecha B3-B5 é onde escalar verba, mesmo com lead mais caro; (2) origem com volume alto e taxa baixa consome agenda de closer sem retorno; (3) indicação costuma fechar plano maior — se não estiver fechando, o programa de indicações merece atenção."),
    ],
    "vendas/ponte": [
        ("_intro", "O que mostra: a resposta à pergunta central — quando a conversão de negociação em contrato está abaixo da meta, a culpa é da QUALIFICAÇÃO que chegou fraca ou do FECHAMENTO?\nComo ler: cada oportunidade do período é cruzada com as características da qualificação que a gerou (velocidade do 1º contato, tempo até virar oportunidade, origem, SDR) e com o closer que a atendeu. A taxa considera só os casos já DECIDIDOS (ganhos + perdidos). A Leitura do especialista compara as variações: taxas muito diferentes conforme a qualificação = gargalo herdado (devolver critérios à Pré-vendas); diferentes só entre closers = fechamento (abordagem, negociação); tudo uniforme = preço/proposta ou volume."),
        ("Por SLA do 1º contato", "O que mostra: a tese da velocidade medida no caixa — oportunidades nascidas de lead atendido em até 15 min fecham a uma taxa; as de lead que esperou mais de 1h, a outra.\nFique de olho: se a diferença for grande, cada minuto de fila da Pré-vendas custa contrato — argumento definitivo para o plantão de resposta."),
        ("Por SDR que qualificou", "O que mostra: a taxa de fechamento EM VENDAS das oportunidades geradas por cada SDR — mede a qualidade do que cada uma entrega, não o volume.\nFique de olho: taxa consistentemente baixa nas oportunidades de uma SDR = revisar os critérios dela; quem agenda muito e fecha pouco pode estar forçando agenda."),
        ("Por closer", "O que mostra: o outro lado da moeda — a mesma qualificação nas mãos de closers diferentes.\nFique de olho: diferença grande entre closers (com volume razoável) = treino individual, não critério de Pré-vendas."),
    ],
    "vendas/winloss": [
        ("_intro", "O que mostra: por que ganhamos e perdemos — os motivos de perda registrados no Pipedrive e, plano a plano, o que mais mata cada um. É a matéria-prima do playbook de objeções."),
        ("Motivos de perda", "O que mostra: o ranking dos motivos registrados nos negócios perdidos.\nFique de olho: (1) o motivo nº 1 merece um roteiro escrito de resposta; (2) 'preço' dominante num plano específico = discussão de precificação, não de vendedor."),
        ("Principais motivos de perda por bundle", "Como ler: um card por plano com os motivos que mais derrubam AQUELE plano, o peso de cada motivo nas perdas dele e a receita perdida.\nFique de olho: (1) motivo dominante num único plano = problema de preço/proposta daquele plano; o mesmo motivo no topo de todos = problema de abordagem ou qualificação do funil inteiro; (2) se B4-B5 morrem por 'timing' e B1 por 'preço', o discurso de valor precisa ser diferente por segmento — um pitch único não serve; (3) o card '(sem plano)' são perdas antes de o campo Produto ser preenchido — normal na fase de reunião; (4) barra grande de '(sem motivo)' = cobrar disciplina de registro antes de qualquer conclusão."),
        ("Diagnóstico dominante", "O que mostra: uma leitura automática do motivo nº 1 de perda — se aponta para PREÇO/ancoragem (conversa de Vendas), para QUALIFICAÇÃO (lead sem prontidão — conversa com a Pré-vendas) ou para algo específico.\nComo ler: gerado por regras determinísticas (palavras-chave do motivo), rotulado como tal — hipótese para investigar, não veredito. Quando metade ou mais dos casos do motivo se concentra num closer, aparece o aviso de treino individual.\nFique de olho: motivo dominante 'sem motivo' = problema de registro no Pipedrive, não de venda."),
        ("Evolução dos motivos", "O que mostra: as perdas por mês (data do fechamento) dos 5 motivos mais frequentes.\nComo ler: o mês corrente é PARCIAL — não conclua por ele.\nFique de olho: motivo novo subindo 2 meses seguidos merece investigação antes de virar o nº 1."),
        ("Origem × motivo", "O que mostra: para cada ORIGEM de lead (linha), o % das perdas dela em cada motivo — responde 'lead dessa origem perde por quê'.\nComo ler: escala por linha (cada origem comparada consigo mesma); célula hachurada = menos de 3 deals (amostra pequena); o nome completo do motivo aparece ao passar o mouse.\nFique de olho: motivo concentrado numa origem = conversa de segmentação com o Marketing; espalhado por todas = processo de Vendas."),
        ("Closer × motivo", "O que mostra: para cada CLOSER (linha), o % das perdas dele em cada motivo — responde 'esse closer perde por quê'.\nComo ler: escala por linha; hachura = menos de 3 deals; nome completo do motivo no mouse.\nFique de olho: motivo concentrado num closer = treino individual; o mesmo motivo dominando todos os closers = problema de processo/oferta, não de pessoa."),
    ],
    "vendas/ciclo": [
        ("_intro", "O que mostra: quanto tempo um negócio leva da criação ao fechamento, e a lista de negociações EMPACADAS — paradas há mais tempo que o normal.\nPor que importa: ciclo longo esfria o cliente e trava a previsibilidade da receita."),
        ("Deals empacados", "O que mostra: as negociações abertas paradas há mais tempo que o padrão.\nFique de olho: (1) é a fila de destrave da coordenação — cada linha merece uma decisão: reativar com prazo ou dar como perdida oficialmente; (2) negociação antiga inflando o pipeline = previsão de receita irreal."),
    ],
    "vendas/closers": [
        ("_intro", "O que mostra: a produtividade individual dos closers (quem é o dono do negócio hoje) — oportunidades, contratos, conversão e ticket, com planos de ação comparados ao padrão do time. Material do 1:1 da Valéria.\nComo funciona: a lista do time é editável no Painel Administrativo — chips identificam coordenação (Valéria) e gerência (Marcos). Desligados (usuário desativado no Pipedrive) saem da lista automaticamente, mas os números deles continuam intactos nas réguas do funil."),
        ("Performance por closer", "Como ler: os números individuais do período. Coordenação e gerência aparecem com chip e ficam FORA da comparação (não são closers a treinar); desligados não aparecem. Ticket em MRR = valor MENSAL do contrato: o B1 é semestral pago à vista, então entra dividido por 6 — sem isso, quem fecha muito B1 pareceria ter ticket alto indevidamente. Ciclo = o tempo típico da 1ª reunião até o contrato.\nFique de olho: (1) ticket MRR alto de verdade = domínio dos planos maiores; (2) conversão abaixo do padrão do time + ciclo longo = negócios presos — veja os empacados dessa pessoa."),
        ("Fechamentos por plano × closer", "O que mostra: os contratos ganhos no período, por plano e por pessoa — quem fecha o quê.\nFique de olho: (1) closer forte em B1 e zerado em B3-B5 = treinar a oferta para cima (a meta da empresa está em B3-B5); (2) se só uma pessoa fecha os planos grandes, há risco de concentração — role-play das reuniões dela com o time."),
        ("Reuniões por closer × hora", "Como ler: quando as reuniões de cada closer acontecem (usamos o momento em que o negócio entrou em Negociação — o card é movido logo após a reunião, então é a melhor aproximação do horário dela). O sombreado é na escala da própria pessoa; a célula contornada é o pico dela.\nFique de olho: (1) cruze com a aba Melhor Horário: se certa janela converte mais, concentre as agendas nela; (2) closer com reuniões espalhadas a noite toda = agenda a organizar com a coordenação."),
        ("Planos de ação individuais", "O que mostra: pontos fortes, fracos e ações por closer, gerados por regra.\nFique de olho: é o ponto de partida do 1:1 — contextualize com o mix de leads e ausências antes de cobrar."),
    ],
    "vendas/horarios": [
        ("_intro", "O que mostra: se existe hora melhor para a REUNIÃO acontecer.\nComo ler: usamos o momento em que o negócio entrou em Negociação (o card é movido logo após a reunião — é a melhor aproximação do horário dela, em Brasília). TAXA = ganhas divididas pelas decididas (ganhas + perdidas): negócios ainda abertos ficam de fora da conta — senão os períodos recentes pareceriam piores só por ainda estarem em andamento. Por isso a taxa daqui pode diferir da taxa do funil.\nAtenção: closer que atualiza os cards em lote infla certos horários."),
        ("Mapa de calor", "Como ler: células escuras = mais reuniões naquele dia/hora; o balão ao passar o mouse traz ganhas, perdidas, em aberto e a taxa.\nFique de olho: volume e conversão são perguntas diferentes — a janela mais cheia não é necessariamente a que mais fecha."),
        ("Conversão por hora da reunião", "Como ler: reuniões, fechadas, perdidas, em aberto e a taxa (sobre as já decididas), hora a hora.\nFique de olho: (1) se uma janela converte consistentemente mais (com volume razoável), priorize-a ao agendar — é argumento para a Pré-vendas oferecer esses horários primeiro; (2) taxas parecidas em todas as horas = o horário não é a variável relevante — não vale reorganizar agenda por isso; (3) muitas 'em aberto' = reuniões recentes, espere antes de concluir."),
    ],
    "vendas/forecast": [
        ("_intro", "O que mostra: a gestão do resultado do mês — as metas por plano (quantidade e R$, da planilha financeira) contra o fechado, com o ritmo, o que falta, o pipeline aberto e a tradução do que falta em oportunidades e leads. O mês é selecionável para revisar históricos."),
        ("Meta realizado por plano", "Como ler: para cada plano (B1-B5 e o total): a meta, o fechado, a receita, o % atingido com a barra de ritmo (o traço marca onde deveríamos estar pelo dia de hoje), o que falta, o pipeline aberto e quantas oportunidades são necessárias no ritmo de conversão dos últimos 90 dias.\nFique de olho: (1) B3-B5 destacados são a prioridade — % total bonito com B4 zerado é meta mal batida; (2) pipeline MENOR que as oportunidades necessárias = matematicamente não fecha sem gerar mais topo de funil AGORA."),
        ("O que falta para bater as metas", "O que mostra: o que falta, traduzido em números acionáveis — quantos contratos faltam → quantas oportunidades isso exige no ritmo atual → quantos leads.\nFique de olho: é o pedido CONCRETO a Pré-vendas e Marketing — sai daqui com número, não com 'precisamos vender mais'."),
    ],
    # ============================= OPERAÇÕES ============================
    "operacoes/iniciativas": [
        ("_intro", "O que mostra: as iniciativas de cada área da empresa no trimestre, sincronizadas do Notion (somente leitura; atualiza todo dia às 06:00 e sob demanda).\nComo ler: agrupado por gestor → iniciativa → escopo → ações com prazo. Cores: verde = concluída · vermelho = prazo vencido · amarelo = andando, no prazo · cinza = sem prazo ou não iniciada. Ação que depende de outra atrasada ganha o aviso 'aguardando ação anterior atrasada'.\nFique de olho: (1) vermelhos concentrados num gestor = conversa de capacidade; (2) muitos 'sem prazo' = plano ainda não operacional; (3) o link ↗ abre a página no Notion para atualizar na fonte."),
        ("Configuração", "O que mostra: um campo por área para colar a URL da página do trimestre no Notion (a busca encontra as bases 'Iniciativas' até 3 níveis abaixo, inclusive subpáginas por gestor).\nAtenção: a página precisa estar compartilhada com a integração no Notion — sem isso a sincronização volta vazia."),
        ("Últimas sincronizações", "O que mostra: o registro de cada sincronização — quando rodou, quantos itens trouxe e os erros.\nFique de olho: sincronização com 0 itens numa área que deveria ter dados = página não compartilhada com a integração, ou URL errada."),
    ],
}

# a Ponte PV→Vendas é ESPELHADA nas duas áreas (14/07: as duas gestoras
# querem a visão) — mesmo conteúdo, mesmo help
HELP["prevendas/ponte"] = HELP["vendas/ponte"]


def _norm(s: str) -> str:
    x = unicodedata.normalize("NFD", (s or "").lower())
    return "".join(c for c in x if unicodedata.category(c) != "Mn")


# rótulo no começo da linha ('O que mostra:', 'Fique de olho:'…) vira negrito
_LBL = re.compile(r"^([A-ZÀ-Ú][^:]{2,32}):\s*(.+)$", re.S)


def _fmt_help(txt: str) -> str:
    """Texto multi-linha → um bloco por linha, com o rótulo em negrito.
    Mantém legível o padrão 'O que mostra / Como ler / Fique de olho'."""
    blocos = []
    for ln in (li.strip() for li in txt.split("\n")):
        if not ln:
            continue
        m = _LBL.match(ln)
        if m:
            blocos.append(f"<div style='margin-top:5px'><b>{escape(m.group(1))}:</b> {escape(m.group(2))}</div>")
        else:
            blocos.append(f"<div style='margin-top:5px'>{escape(ln)}</div>")
    return "".join(blocos)


def _hint(campo: str, txt: str) -> str:
    return ("<details style='margin:2px 0 8px'><summary style='cursor:pointer;font-size:var(--fs-2xs);"
            "color:var(--brand)'>ⓘ como ler este campo</summary>"
            f"<div style='margin:5px 0 0;padding:8px 12px;background:var(--surface-1);border-left:3px solid var(--brand);"
            f"border-radius:var(--radius-sm);font-size:var(--fs-xs);color:var(--text-2);line-height:1.55'>"
            f"<b>{escape(campo)}</b>{_fmt_help(txt)}</div></details>")


def inject_help(area: str, view: str, content: str) -> str:
    """_intro → painel 'O que você encontra nesta página' no topo; demais itens
    ancorados SOB o <h2> correspondente (match por tokens, sem acento); itens
    sem âncora caem no painel do topo junto do intro."""
    itens = HELP.get(f"{area}/{view}")
    if not itens:
        return content
    intro = next((t for c, t in itens if c == "_intro"), None)
    sobras: list[tuple[str, str]] = []
    for campo, txt in itens:
        if campo == "_intro":
            continue
        toks = [t for t in _norm(campo).split() if len(t) > 3]
        achou = None
        for m in re.finditer(r"<h2[^>]*>(.*?)</h2>(\s*<p class=secsub>.*?</p>)?", content, re.S):
            h2 = _norm(re.sub(r"<[^>]+>", "", m.group(1)))
            if toks and all(t in h2 for t in toks):
                achou = m
                break
        if achou:
            fim = achou.end()
            content = content[:fim] + _hint(campo, txt) + content[fim:]
        else:
            sobras.append((campo, txt))
    if intro or sobras:
        corpo = ""
        if intro:
            corpo += (f"<div style='font-size:var(--fs-sm);line-height:1.6;color:var(--text-2)'>{_fmt_help(intro)}</div>")
        corpo += "".join(
            f"<div style='padding:6px 0;border-top:1px solid var(--border);font-size:var(--fs-sm);line-height:1.55'>"
            f"<b>{escape(c)}</b>{_fmt_help(t)}</div>"
            for c, t in sobras)
        content = (
            "<details style='margin:14px 0;background:var(--surface-1);border:1px solid var(--border-mid);"
            "border-left:3px solid var(--brand);border-radius:var(--radius-md);padding:10px 16px'>"
            "<summary style='cursor:pointer;font-size:var(--fs-sm);font-weight:600;color:var(--text-2)'>"
            "❓ O que você encontra nesta página</summary>"
            f"<div style='margin-top:8px'>{corpo}</div></details>") + content
    return content


def help_panel(area: str, view: str) -> str:
    """Compatibilidade (cascas antigas) — a injeção real é inject_help."""
    return ""
